### ISSUE TITLE
Clean up bidix

### ISSUE THREAD

**Issue by ftyers** [apertium/apertium-chv-tat#1]
* Remove direction restrictions that are based on semantics as opposed to structural stuff 
  * Move these into the `.lrx` files.
* Remove lines with Tatar translations that are not found in `apertium-tat.tat.lexc`. Save these in a file in the `dev/` directory

**Comment by qavan** [comment]
LR\RL removed by reason of wrong adding
filtered(clean up):N,NP,V,ADV,ADJ
in "dev\ostatok" is rest of non-clean-up pairs(little others)
my english lmao

**Comment by qavan** [comment]
Closed by 232a303.
Check \dev\clean up

**Comment by qavan** [comment]
Closed by 232a303.
Check \dev\clean up
